#! /bin/sh

# ----------------------- #
# BSPWM CONFIGURATION     # 
# ----------------------- #

if [ $(xrandr -q | grep "HDMI-1 connected" | cut -d ' ' -f1) = "HDMI-1" ]; then
	xrandr --output HDMI-1 --primary --auto --rotate normal --output eDP-1 --auto --rotate normal
	xrandr --output eDP-1 --primary --auto --rotate normal --left-of HDMI-1
else
	xrandr --output eDP-1 --primary --auto --rotate normal
fi

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

bspc config border_radius                 0
bspc config border_width                  2
bspc config window_gap                    4

bspc config top_padding                   32
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config paddingless_monocle 	      true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config ignore_ewmh_focus 		      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

## BSPWM COLORS ======================== #
bspc config normal_border_color "#1E1E2E"
bspc config active_border_color " #1E1E2E"
bspc config focused_border_color "#96CDFB"
bspc config presel_feedback_color "#96CDFB"

## BSPWM RULES ========================== # 

if [ $(xrandr -q | grep "HDMI-1 connected" | cut -d ' ' -f1) = "HDMI-1" ]; then
	bspc rule -a Brave-browser desktop=^7 state=tiled follow=false
	bspc rule -a discord state=tiled desktop=^4 follow=false
	bspc rule -a TelegramDesktop state=tiled desktop=^4 follow=false
	bspc rule -a Rhythmbox state=tiled desktop=^5 follow=on
	bspc rule -a Code state=tiled desktop=^6 follow=on
	bspc rule -a Pulsemixer state=tiled desktop=^5 follow=on
else
	bspc rule -a Brave-browser desktop=^2 state=tiled follow=false
	bspc rule -a discord state=tiled desktop=^4 follow=false
	bspc rule -a TelegramDesktop state=floating desktop=^4 follow=false
	bspc rule -a Rhythmbox state=tiled desktop=^5 follow=on
	bspc rule -a Code state=tiled desktop=^1 follow=on
	bspc rule -a Pulsemixer state=tiled desktop=^5 follow=on
fi

bspc rule -a vlc state=floating
bspc rule -a Thunar state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Timeshift-gtk state=floating follow=on
bspc rule -a Xfce4-power-manager-settings state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a stacer state=floating
bspc rule -a Gpick state=floating follow=on

## AUTOSTART PROGRAMS ======================== # 
pgrep -x sxhkd > /dev/null || sxhkd &
feh  --bg-fill /home/rockdri/Imágenes/Wallpapers/BosqueAmanecer.jpg &
~/.config/polybar/./launch.sh &
picom --experimental-backends &
xfce4-power-manager &
greenclip daemon &
dunst &
ibus-daemon -drxR &